### ISSUE TITLE
keepnick.py is failing on weechat 1.9.1

### ISSUE THREAD

**Issue by noqqe** [weechatter/weechat-scripts#21]
Just installed it and it says:

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/data/.weechat/python/keepnick.py", line 147, in redirect_isonhandler
python: stdout/stderr:     grabnick_and_auth(hashtable['server'], nick)
python: stdout/stderr:   File "/data/.weechat/python/keepnick.py", line 224, in grabnick_and_auth
python: stdout/stderr:     grabnick(servername, nick)  # get your nick back
python: stdout/stderr:   File "/data/.weechat/python/keepnick.py", line 241, in grabnick
python: stdout/stderr:     weechat.command(weechat.buffer_search('irc','%s.%s' % ('server',servername)), OPTIONS['command'] % nick)
python: stdout/stderr: TypeError: not all arguments converted during string formatting
python: error in function "redirect_isonhandler"
```

when its trying to fix my nick. Any Ideas?

**Comment by weechatter** [comment]
version of script?

**Comment by noqqe** [comment]
Its 1.6

**Comment by weechatter** [comment]
i can not reproduce. maybe some wrong settings, please check:
/set plugins.var.python.keepnick*

**Comment by noqqe** [comment]
```
[var] (plugins.conf)
  plugins.var.python.keepnick.command = "/nick noqqe"
  plugins.var.python.keepnick.debug = "off"
  plugins.var.python.keepnick.delay = "600"
  plugins.var.python.keepnick.nickserv = "/msg -server $server NICKSERV IDENTIFY $passwd"
  plugins.var.python.keepnick.serverlist = "freenode"
  plugins.var.python.keepnick.text = "Nickstealer left Network: %s!"
  plugins.var.python.keepnick.timeout = "60"
```

**Comment by weechatter** [comment]
name of variable changed in 1.5 (add evaluation for option "text" and use variable "$server" instead of "%s"), try:
/set plugins.var.python.keepnick.text "Nickstealer left Network: $server!"

also better use, instead of a hard-coded nick name:
/set plugins.var.python.keepnick.command "/nick %s"

but i'll check the problem with "%s", should not print an error message
